server:
  servlet:
    encoding:
      force-response: true

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/likelion-db
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  profiles:
    include: oauth

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui # 접속 path 설정
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

spotify:
  client:
    id:
      1234
    secret:
      1234

# multipart 설정
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

# aws 설정
# 사용할 S3 bucket region 입력
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: abcdefg

iamAccessKey: 1234
iamSecretKey: 1234